package(
    default_visibility = ["//fleetbench:__subpackages__"],
)

cc_library(
    name = "common",
    hdrs = [
        "common.h",
    ],
    linkstatic = 1,
    deps = [
        "@com_google_absl//absl/random",
    ],
    alwayslink = 1,
)
