// Copyright 2025 The Fleetbench Authors
//
// Licensed under the Apache License, Version 2.0 (the "License" );
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// WARNING: DO NOT EDIT! This file is auto-generated.

#include "fleetbench/proto/lifecycle.h"

#include <cstddef>
#include <cstdint>
#include <string>
#include <vector>

#include "fleetbench/proto/access_message0.h"
#include "fleetbench/proto/access_message1.h"
#include "fleetbench/proto/access_message10.h"
#include "fleetbench/proto/access_message11.h"
#include "fleetbench/proto/access_message12.h"
#include "fleetbench/proto/access_message13.h"
#include "fleetbench/proto/access_message14.h"
#include "fleetbench/proto/access_message15.h"
#include "fleetbench/proto/access_message16.h"
#include "fleetbench/proto/access_message17.h"
#include "fleetbench/proto/access_message18.h"
#include "fleetbench/proto/access_message19.h"
#include "fleetbench/proto/access_message2.h"
#include "fleetbench/proto/access_message3.h"
#include "fleetbench/proto/access_message4.h"
#include "fleetbench/proto/access_message5.h"
#include "fleetbench/proto/access_message6.h"
#include "fleetbench/proto/access_message7.h"
#include "fleetbench/proto/access_message8.h"
#include "fleetbench/proto/access_message9.h"
#include "fleetbench/proto/receiver.h"
#include "google/protobuf/arena.h"
namespace fleetbench::proto {

ProtoLifecycle::ProtoLifecycle(uint32_t working_set_size)
    : working_set_size_(working_set_size),
      s_(kMaxValueStringSize, 'a'),
      indices_(working_set_size) {
  Resize(message0_);
  Resize(message1_);
  Resize(message2_);
  Resize(message3_);
  Resize(message4_);
  Resize(message5_);
  Resize(message6_);
  Resize(message7_);
  Resize(message8_);
  Resize(message9_);
  Resize(message10_);
  Resize(message11_);
  Resize(message12_);
  Resize(message13_);
  Resize(message14_);
  Resize(message15_);
  Resize(message16_);
  Resize(message17_);
  Resize(message18_);
  Resize(message19_);
}

template <typename T>
void ProtoLifecycle::InitMessages(std::vector<T*>& messages,
                                  std::vector<T*>& other_messages,
                                  std::vector<std::string>& strings,
                                  google::protobuf::Arena* arena) {
  for (size_t i = 0; i < working_set_size_; i++) {
    messages[i] = google::protobuf::Arena::Create<T>(arena);
    other_messages[i] = google::protobuf::Arena::Create<T>(arena);
    strings[i].clear();
  }
}
void ProtoLifecycle::Init(google::protobuf::Arena* arena) {
  arena_ = arena;
  // Declare variables for lifecycles.
  InitMessages(message0_.message, message0_.other_message, message0_.string,
               arena);
  InitMessages(message1_.message, message1_.other_message, message1_.string,
               arena);
  InitMessages(message2_.message, message2_.other_message, message2_.string,
               arena);
  InitMessages(message3_.message, message3_.other_message, message3_.string,
               arena);
  InitMessages(message4_.message, message4_.other_message, message4_.string,
               arena);
  InitMessages(message5_.message, message5_.other_message, message5_.string,
               arena);
  InitMessages(message6_.message, message6_.other_message, message6_.string,
               arena);
  InitMessages(message7_.message, message7_.other_message, message7_.string,
               arena);
  InitMessages(message8_.message, message8_.other_message, message8_.string,
               arena);
  InitMessages(message9_.message, message9_.other_message, message9_.string,
               arena);
  InitMessages(message10_.message, message10_.other_message, message10_.string,
               arena);
  InitMessages(message11_.message, message11_.other_message, message11_.string,
               arena);
  InitMessages(message12_.message, message12_.other_message, message12_.string,
               arena);
  InitMessages(message13_.message, message13_.other_message, message13_.string,
               arena);
  InitMessages(message14_.message, message14_.other_message, message14_.string,
               arena);
  InitMessages(message15_.message, message15_.other_message, message15_.string,
               arena);
  InitMessages(message16_.message, message16_.other_message, message16_.string,
               arena);
  InitMessages(message17_.message, message17_.other_message, message17_.string,
               arena);
  InitMessages(message18_.message, message18_.other_message, message18_.string,
               arena);
  InitMessages(message19_.message, message19_.other_message, message19_.string,
               arena);
  // Initialize other_message instance of messages
  for (size_t i = 0; i < working_set_size_; i++) {
    Message0_Set_1(message0_.other_message[i], &s_);
    Message1_Set_1(message1_.other_message[i], &s_);
    Message2_Set_1(message2_.other_message[i], &s_);
    Message3_Set_1(message3_.other_message[i], &s_);
    Message4_Set_1(message4_.other_message[i], &s_);
    Message5_Set_1(message5_.other_message[i], &s_);
    Message6_Set_1(message6_.other_message[i], &s_);
    Message7_Set_1(message7_.other_message[i], &s_);
    Message8_Set_1(message8_.other_message[i], &s_);
    Message9_Set_1(message9_.other_message[i], &s_);
    Message10_Set_1(message10_.other_message[i], &s_);
    Message11_Set_1(message11_.other_message[i], &s_);
    Message12_Set_1(message12_.other_message[i], &s_);
    Message13_Set_1(message13_.other_message[i], &s_);
    Message14_Set_1(message14_.other_message[i], &s_);
    Message15_Set_1(message15_.other_message[i], &s_);
    Message16_Set_1(message16_.other_message[i], &s_);
    Message17_Set_1(message17_.other_message[i], &s_);
    Message18_Set_1(message18_.other_message[i], &s_);
    Message19_Set_1(message19_.other_message[i], &s_);
  }
}

void ProtoLifecycle::Run() {
  for (size_t i = 0; i < working_set_size_; i++) {
    Create(message15_.message[i]);
    Create(message8_.message[i]);
    Create(message19_.message[i]);
    Create(message12_.message[i]);
    Deserialize(message19_.message[i], &message19_.string[i]);
    Create(message6_.message[i]);
    Create(message11_.message[i]);
    Create(message0_.message[i]);
    Create(message18_.message[i]);
    Create(message1_.message[i]);
    Create(message14_.message[i]);
    Serialize(message8_.other_message[i], &message8_.string[i]);
    Create(message5_.message[i]);
    Copy(message11_.message[i], message11_.other_message[i]);
    Serialize(message15_.message[i], &message15_.string[i]);
    Create(message7_.message[i]);
    Copy(message18_.message[i], message18_.other_message[i]);
    Copy(message15_.message[i], message15_.other_message[i]);
    Create(message10_.message[i]);
    Serialize(message14_.other_message[i], &message14_.string[i]);
    Create(message9_.message[i]);
    Copy(message14_.message[i], message14_.other_message[i]);
    Copy(message10_.message[i], message10_.other_message[i]);
    Copy(message8_.message[i], message8_.other_message[i]);
    Destroy(message6_.message[i]);
    message6_.message[i] = google::protobuf::Arena::Create<Message6>(arena_);
    Message6_Set_2(message6_.message[i], &s_);
    Message7_Set_2(message7_.other_message[i], &s_);
    Destroy(message11_.other_message[i]);
    message11_.other_message[i] = google::protobuf::Arena::Create<Message11>(arena_);
    Message11_Set_2(message11_.other_message[i], &s_);
    Descriptor(message19_.message[i]);
    Create(message3_.message[i]);
    Create(message16_.message[i]);
    Reflection(message14_.message[i]);
    Create(message2_.message[i]);
    Destroy(message9_.other_message[i]);
    message9_.other_message[i] = google::protobuf::Arena::Create<Message9>(arena_);
    Message9_Set_2(message9_.other_message[i], &s_);
    ByteSize(message7_.message[i]);
    Copy(message6_.message[i], message6_.other_message[i]);
    Descriptor(message12_.message[i]);
    Create(message13_.message[i]);
    Serialize(message7_.other_message[i], &message7_.string[i]);
    Serialize(message16_.message[i], &message16_.string[i]);
    Merge(message7_.message[i], message7_.other_message[i]);
    Reflection(message1_.message[i]);
    Create(message17_.message[i]);
    Copy(message9_.message[i], message9_.other_message[i]);
    Serialize(message0_.other_message[i], &message0_.string[i]);
    Descriptor(message5_.message[i]);
    Create(message4_.message[i]);
    Merge(message14_.message[i], message14_.other_message[i]);
    Copy(message17_.message[i], message17_.other_message[i]);
    Copy(message10_.message[i], message10_.other_message[i]);
    Destroy(message7_.message[i]);
    message7_.message[i] = google::protobuf::Arena::Create<Message7>(arena_);
    Message7_Set_2(message7_.message[i], &s_);
    Reflection(message7_.message[i]);
    Deserialize(message18_.message[i], &message18_.string[i]);
    Reflection(message4_.message[i]);
    Destroy(message11_.message[i]);
    message11_.message[i] = google::protobuf::Arena::Create<Message11>(arena_);
    Message11_Set_2(message11_.message[i], &s_);
    Reflection(message0_.message[i]);
    Message0_Set_2(message0_.other_message[i], &s_);
    Copy(message2_.message[i], message2_.other_message[i]);
    Descriptor(message8_.message[i]);
    Serialize(message14_.message[i], &message14_.string[i]);
    Descriptor(message3_.message[i]);
    Copy(message15_.message[i], message15_.other_message[i]);
    Copy(message0_.message[i], message0_.other_message[i]);
    Swap(message7_.message[i], message7_.other_message[i]);
    Reflection(message1_.message[i]);
    Copy(message16_.message[i], message16_.other_message[i]);
    Copy(message16_.message[i], message16_.other_message[i]);
    Reflection(message18_.message[i]);
    Deserialize(message4_.other_message[i], &message4_.string[i]);
    Reflection(message16_.message[i]);
    Destroy(message19_.message[i]);
    message19_.message[i] = google::protobuf::Arena::Create<Message19>(arena_);
    Message19_Set_2(message19_.message[i], &s_);
    Serialize(message16_.other_message[i], &message16_.string[i]);
    ByteSize(message4_.message[i]);
    Destroy(message0_.message[i]);
    message0_.message[i] = google::protobuf::Arena::Create<Message0>(arena_);
    Message0_Set_2(message0_.message[i], &s_);
    Reflection(message11_.message[i]);
    Message1_Set_2(message1_.other_message[i], &s_);
    Copy(message4_.message[i], message4_.other_message[i]);
    Copy(message4_.message[i], message4_.other_message[i]);
    Reflection(message5_.message[i]);
    Copy(message6_.message[i], message6_.other_message[i]);
    Copy(message14_.message[i], message14_.other_message[i]);
    Serialize(message11_.message[i], &message11_.string[i]);
    Serialize(message4_.other_message[i], &message4_.string[i]);
    Destroy(message17_.message[i]);
    message17_.message[i] = google::protobuf::Arena::Create<Message17>(arena_);
    Message17_Set_2(message17_.message[i], &s_);
    Reflection(message0_.message[i]);
    Descriptor(message9_.message[i]);
    Reflection(message11_.message[i]);
    Copy(message11_.message[i], message11_.other_message[i]);
    ByteSize(message6_.message[i]);
    Reflection(message11_.message[i]);
    Message6_Get_1(message6_.message[i]);
    Reflection(message9_.message[i]);
    Message19_Set_2(message19_.other_message[i], &s_);
    Reflection(message5_.message[i]);
    Message9_Set_2(message9_.other_message[i], &s_);
    Deserialize(message10_.other_message[i], &message10_.string[i]);
    Swap(message3_.message[i], message3_.other_message[i]);
    Merge(message17_.message[i], message17_.other_message[i]);
    Copy(message14_.message[i], message14_.other_message[i]);
    Copy(message13_.message[i], message13_.other_message[i]);
    Reflection(message4_.message[i]);
    Reflection(message10_.message[i]);
    Message5_Set_2(message5_.other_message[i], &s_);
    Copy(message11_.message[i], message11_.other_message[i]);
    Message12_Set_2(message12_.message[i], &s_);
    Message6_Set_2(message6_.other_message[i], &s_);
    Descriptor(message4_.message[i]);
    ByteSize(message15_.message[i]);
    Reflection(message14_.message[i]);
    Destroy(message2_.other_message[i]);
    message2_.other_message[i] = google::protobuf::Arena::Create<Message2>(arena_);
    Message2_Set_2(message2_.other_message[i], &s_);
    Descriptor(message18_.message[i]);
    Deserialize(message8_.other_message[i], &message8_.string[i]);
    Message7_Get_1(message7_.message[i]);
    Message5_Set_3(message5_.message[i], &s_);
    Reflection(message6_.message[i]);
    Destroy(message8_.message[i]);
    message8_.message[i] = google::protobuf::Arena::Create<Message8>(arena_);
    Message8_Set_2(message8_.message[i], &s_);
    Reflection(message0_.message[i]);
    Destroy(message12_.message[i]);
    message12_.message[i] = google::protobuf::Arena::Create<Message12>(arena_);
    Message12_Set_2(message12_.message[i], &s_);
    Copy(message8_.message[i], message8_.other_message[i]);
    Serialize(message15_.message[i], &message15_.string[i]);
    Copy(message13_.message[i], message13_.other_message[i]);
    Destroy(message16_.message[i]);
    message16_.message[i] = google::protobuf::Arena::Create<Message16>(arena_);
    Message16_Set_2(message16_.message[i], &s_);
    Reflection(message7_.message[i]);
    Descriptor(message17_.message[i]);
    Reflection(message3_.message[i]);
    Deserialize(message0_.other_message[i], &message0_.string[i]);
    Reflection(message19_.message[i]);
    Reflection(message11_.message[i]);
    Message7_Get_2(message7_.message[i]);
    Destroy(message18_.message[i]);
    message18_.message[i] = google::protobuf::Arena::Create<Message18>(arena_);
    Message18_Set_2(message18_.message[i], &s_);
    ByteSize(message17_.message[i]);
    Message0_Set_3(message0_.message[i], &s_);
    Descriptor(message7_.message[i]);
    Deserialize(message0_.other_message[i], &message0_.string[i]);
    Descriptor(message12_.message[i]);
    Destroy(message19_.message[i]);
    message19_.message[i] = google::protobuf::Arena::Create<Message19>(arena_);
    Message19_Set_2(message19_.message[i], &s_);
    Reflection(message11_.message[i]);
    Copy(message16_.message[i], message16_.other_message[i]);
    Copy(message10_.message[i], message10_.other_message[i]);
    Descriptor(message11_.message[i]);
    Message12_Set_3(message12_.message[i], &s_);
    Serialize(message6_.other_message[i], &message6_.string[i]);
    Reflection(message10_.message[i]);
    Reflection(message10_.message[i]);
    Reflection(message11_.message[i]);
    Reflection(message11_.message[i]);
    Reflection(message4_.message[i]);
    Deserialize(message6_.other_message[i], &message6_.string[i]);
    Descriptor(message2_.message[i]);
    Reflection(message5_.message[i]);
    ByteSize(message11_.message[i]);
    Copy(message5_.message[i], message5_.other_message[i]);
    Serialize(message14_.other_message[i], &message14_.string[i]);
    Serialize(message3_.message[i], &message3_.string[i]);
    Reflection(message12_.message[i]);
    Reflection(message6_.message[i]);
    Reflection(message15_.message[i]);
    ByteSize(message4_.message[i]);
    Reflection(message16_.message[i]);
    Merge(message9_.message[i], message9_.other_message[i]);
    Deserialize(message6_.message[i], &message6_.string[i]);
    Message14_Set_2(message14_.other_message[i], &s_);
    Message19_Get_1(message19_.message[i]);
    Merge(message19_.message[i], message19_.other_message[i]);
    ByteSize(message8_.message[i]);
    Copy(message5_.message[i], message5_.other_message[i]);
    Copy(message9_.message[i], message9_.other_message[i]);
    Message3_Set_2(message3_.other_message[i], &s_);
    Copy(message12_.message[i], message12_.other_message[i]);
    Destroy(message2_.message[i]);
    message2_.message[i] = google::protobuf::Arena::Create<Message2>(arena_);
    Message2_Set_2(message2_.message[i], &s_);
    Reflection(message0_.message[i]);
    Message2_Set_2(message2_.message[i], &s_);
    Reflection(message4_.message[i]);
    Copy(message4_.message[i], message4_.other_message[i]);
    Reflection(message12_.message[i]);
    ByteSize(message9_.message[i]);
    Reflection(message6_.message[i]);
    Reflection(message10_.message[i]);
    Copy(message6_.message[i], message6_.other_message[i]);
    Copy(message0_.message[i], message0_.other_message[i]);
    Copy(message3_.message[i], message3_.other_message[i]);
    Reflection(message13_.message[i]);
    Reflection(message14_.message[i]);
    Serialize(message6_.message[i], &message6_.string[i]);
    ByteSize(message3_.message[i]);
    Copy(message7_.message[i], message7_.other_message[i]);
    Reflection(message15_.message[i]);
    Reflection(message11_.message[i]);
    Copy(message18_.message[i], message18_.other_message[i]);
    Reflection(message7_.message[i]);
    Deserialize(message2_.message[i], &message2_.string[i]);
    Reflection(message12_.message[i]);
    Reflection(message5_.message[i]);
    Deserialize(message15_.other_message[i], &message15_.string[i]);
    Deserialize(message1_.other_message[i], &message1_.string[i]);
    Reflection(message2_.message[i]);
    Reflection(message16_.message[i]);
    Copy(message15_.message[i], message15_.other_message[i]);
    Reflection(message0_.message[i]);
    ByteSize(message19_.message[i]);
    Serialize(message12_.message[i], &message12_.string[i]);
    Reflection(message1_.message[i]);
    Copy(message5_.message[i], message5_.other_message[i]);
    Deserialize(message4_.other_message[i], &message4_.string[i]);
    Deserialize(message14_.message[i], &message14_.string[i]);
    Reflection(message8_.message[i]);
    Copy(message13_.message[i], message13_.other_message[i]);
    Merge(message19_.message[i], message19_.other_message[i]);
    Descriptor(message14_.message[i]);
    Copy(message3_.message[i], message3_.other_message[i]);
    Reflection(message7_.message[i]);
    Reflection(message3_.message[i]);
    Reflection(message19_.message[i]);
    Serialize(message18_.message[i], &message18_.string[i]);
    Deserialize(message19_.message[i], &message19_.string[i]);
    Reflection(message19_.message[i]);
    Descriptor(message15_.message[i]);
    Copy(message1_.message[i], message1_.other_message[i]);
    Message12_Set_4(message12_.other_message[i], &s_);
    Reflection(message16_.message[i]);
    Merge(message4_.message[i], message4_.other_message[i]);
    Reflection(message7_.message[i]);
    Message0_Get_1(message0_.message[i]);
    ByteSize(message12_.message[i]);
    Copy(message4_.message[i], message4_.other_message[i]);
    Message18_Set_2(message18_.message[i], &s_);
    Reflection(message18_.message[i]);
    Copy(message9_.message[i], message9_.other_message[i]);
    Reflection(message10_.message[i]);
    Serialize(message10_.message[i], &message10_.string[i]);
    Reflection(message10_.message[i]);
    Deserialize(message11_.other_message[i], &message11_.string[i]);
    ByteSize(message9_.message[i]);
    Reflection(message4_.message[i]);
    Serialize(message10_.other_message[i], &message10_.string[i]);
    Copy(message19_.message[i], message19_.other_message[i]);
    Copy(message8_.message[i], message8_.other_message[i]);
    Reflection(message13_.message[i]);
    Descriptor(message16_.message[i]);
    Reflection(message1_.message[i]);
    Reflection(message18_.message[i]);
    Reflection(message8_.message[i]);
    Destroy(message16_.other_message[i]);
    message16_.other_message[i] = google::protobuf::Arena::Create<Message16>(arena_);
    Message16_Set_2(message16_.other_message[i], &s_);
    Reflection(message14_.message[i]);
    Reflection(message10_.message[i]);
    Reflection(message15_.message[i]);
    Copy(message8_.message[i], message8_.other_message[i]);
    Copy(message9_.message[i], message9_.other_message[i]);
    Copy(message15_.message[i], message15_.other_message[i]);
    Copy(message13_.message[i], message13_.other_message[i]);
    Reflection(message4_.message[i]);
    ByteSize(message2_.message[i]);
    Descriptor(message7_.message[i]);
    Reflection(message3_.message[i]);
    Reflection(message8_.message[i]);
    Copy(message13_.message[i], message13_.other_message[i]);
    Copy(message9_.message[i], message9_.other_message[i]);
    Destroy(message11_.other_message[i]);
    message11_.other_message[i] = google::protobuf::Arena::Create<Message11>(arena_);
    Message11_Set_2(message11_.other_message[i], &s_);
    Descriptor(message14_.message[i]);
    Descriptor(message0_.message[i]);
    Copy(message0_.message[i], message0_.other_message[i]);
    Reflection(message17_.message[i]);
    Reflection(message16_.message[i]);
    Reflection(message15_.message[i]);
    Reflection(message3_.message[i]);
    Descriptor(message3_.message[i]);
    Destroy(message19_.other_message[i]);
    message19_.other_message[i] = google::protobuf::Arena::Create<Message19>(arena_);
    Message19_Set_2(message19_.other_message[i], &s_);
    Reflection(message2_.message[i]);
    Message10_Set_2(message10_.message[i], &s_);
    Copy(message1_.message[i], message1_.other_message[i]);
    Reflection(message0_.message[i]);
    Message0_Get_2(message0_.message[i]);
    ByteSize(message16_.message[i]);
    Copy(message14_.message[i], message14_.other_message[i]);
    Copy(message7_.message[i], message7_.other_message[i]);
    Copy(message3_.message[i], message3_.other_message[i]);
    Reflection(message8_.message[i]);
    ByteSize(message2_.message[i]);
    ByteSize(message2_.message[i]);
    Reflection(message17_.message[i]);
    Copy(message16_.message[i], message16_.other_message[i]);
    Reflection(message8_.message[i]);
    Copy(message6_.message[i], message6_.other_message[i]);
    Deserialize(message1_.message[i], &message1_.string[i]);
    Copy(message12_.message[i], message12_.other_message[i]);
    Descriptor(message17_.message[i]);
    ByteSize(message12_.message[i]);
    Copy(message19_.message[i], message19_.other_message[i]);
    Copy(message11_.message[i], message11_.other_message[i]);
    Copy(message6_.message[i], message6_.other_message[i]);
    Reflection(message0_.message[i]);
    Reflection(message11_.message[i]);
    Copy(message17_.message[i], message17_.other_message[i]);
    Descriptor(message2_.message[i]);
    Serialize(message6_.message[i], &message6_.string[i]);
    Copy(message4_.message[i], message4_.other_message[i]);
    Serialize(message13_.other_message[i], &message13_.string[i]);
    Descriptor(message18_.message[i]);
    Destroy(message15_.message[i]);
    message15_.message[i] = google::protobuf::Arena::Create<Message15>(arena_);
    Message15_Set_2(message15_.message[i], &s_);
    Message9_Get_1(message9_.message[i]);
    Reflection(message9_.message[i]);
    Destroy(message5_.message[i]);
    message5_.message[i] = google::protobuf::Arena::Create<Message5>(arena_);
    Message5_Set_2(message5_.message[i], &s_);
    SpaceUsed(message8_.message[i]);
    Reflection(message15_.message[i]);
    Destroy(message5_.other_message[i]);
    message5_.other_message[i] = google::protobuf::Arena::Create<Message5>(arena_);
    Message5_Set_2(message5_.other_message[i], &s_);
    Reflection(message7_.message[i]);
    Reflection(message13_.message[i]);
    Descriptor(message4_.message[i]);
    Reflection(message6_.message[i]);
    Copy(message8_.message[i], message8_.other_message[i]);
    Copy(message15_.message[i], message15_.other_message[i]);
    Descriptor(message12_.message[i]);
    Copy(message17_.message[i], message17_.other_message[i]);
    Destroy(message7_.message[i]);
    message7_.message[i] = google::protobuf::Arena::Create<Message7>(arena_);
    Message7_Set_2(message7_.message[i], &s_);
    Copy(message13_.message[i], message13_.other_message[i]);
    Descriptor(message0_.message[i]);
    Reflection(message8_.message[i]);
    Reflection(message3_.message[i]);
    Destroy(message7_.other_message[i]);
    message7_.other_message[i] = google::protobuf::Arena::Create<Message7>(arena_);
    Message7_Set_2(message7_.other_message[i], &s_);
    Copy(message4_.message[i], message4_.other_message[i]);
    Reflection(message13_.message[i]);
    Message13_Get_1(message13_.message[i]);
    Message16_Set_2(message16_.message[i], &s_);
    Copy(message16_.message[i], message16_.other_message[i]);
    Descriptor(message15_.message[i]);
    Copy(message0_.message[i], message0_.other_message[i]);
    Deserialize(message17_.message[i], &message17_.string[i]);
    Destroy(message11_.message[i]);
    message11_.message[i] = google::protobuf::Arena::Create<Message11>(arena_);
    Message11_Set_2(message11_.message[i], &s_);
    Merge(message0_.message[i], message0_.other_message[i]);
    Reflection(message17_.message[i]);
    Descriptor(message7_.message[i]);
    Destroy(message12_.message[i]);
    message12_.message[i] = google::protobuf::Arena::Create<Message12>(arena_);
    Message12_Set_2(message12_.message[i], &s_);
    Descriptor(message15_.message[i]);
    Swap(message19_.message[i], message19_.other_message[i]);
    Reflection(message3_.message[i]);
    Message18_Set_3(message18_.message[i], &s_);
    Reflection(message18_.message[i]);
    ByteSize(message9_.message[i]);
    Copy(message13_.message[i], message13_.other_message[i]);
    Descriptor(message3_.message[i]);
    Descriptor(message3_.message[i]);
    Message18_Get_1(message18_.message[i]);
    Reflection(message9_.message[i]);
    Reflection(message1_.message[i]);
    Copy(message5_.message[i], message5_.other_message[i]);
    Destroy(message2_.other_message[i]);
    message2_.other_message[i] = google::protobuf::Arena::Create<Message2>(arena_);
    Message2_Set_2(message2_.other_message[i], &s_);
    Message11_Set_2(message11_.other_message[i], &s_);
    Destroy(message4_.other_message[i]);
    message4_.other_message[i] = google::protobuf::Arena::Create<Message4>(arena_);
    Message4_Set_2(message4_.other_message[i], &s_);
    Merge(message8_.message[i], message8_.other_message[i]);
    Descriptor(message11_.message[i]);
    Descriptor(message3_.message[i]);
    Descriptor(message11_.message[i]);
    Deserialize(message9_.message[i], &message9_.string[i]);
    Copy(message0_.message[i], message0_.other_message[i]);
    Message5_Set_4(message5_.other_message[i], &s_);
    Reflection(message6_.message[i]);
    Message1_Get_1(message1_.message[i]);
    Serialize(message5_.other_message[i], &message5_.string[i]);
    Reflection(message13_.message[i]);
    Copy(message9_.message[i], message9_.other_message[i]);
    Swap(message8_.message[i], message8_.other_message[i]);
    Copy(message18_.message[i], message18_.other_message[i]);
    ByteSize(message17_.message[i]);
    Serialize(message15_.other_message[i], &message15_.string[i]);
    Copy(message16_.message[i], message16_.other_message[i]);
    Reflection(message18_.message[i]);
    Reflection(message15_.message[i]);
    Copy(message7_.message[i], message7_.other_message[i]);
    Descriptor(message3_.message[i]);
    Reflection(message12_.message[i]);
    Copy(message10_.message[i], message10_.other_message[i]);
    Reflection(message7_.message[i]);
    Destroy(message2_.other_message[i]);
    message2_.other_message[i] = google::protobuf::Arena::Create<Message2>(arena_);
    Message2_Set_2(message2_.other_message[i], &s_);
    Copy(message10_.message[i], message10_.other_message[i]);
    Deserialize(message9_.other_message[i], &message9_.string[i]);
    Serialize(message6_.message[i], &message6_.string[i]);
    ByteSize(message4_.message[i]);
    Message9_Get_2(message9_.message[i]);
    Message18_Get_2(message18_.message[i]);
    Reflection(message13_.message[i]);
    Message6_Get_2(message6_.message[i]);
    Copy(message12_.message[i], message12_.other_message[i]);
    Reflection(message14_.message[i]);
    Message15_Get_1(message15_.message[i]);
    Serialize(message6_.other_message[i], &message6_.string[i]);
    Reflection(message12_.message[i]);
    Copy(message19_.message[i], message19_.other_message[i]);
    Reflection(message9_.message[i]);
    Descriptor(message18_.message[i]);
    Copy(message13_.message[i], message13_.other_message[i]);
    Descriptor(message9_.message[i]);
    Reflection(message16_.message[i]);
    Merge(message9_.message[i], message9_.other_message[i]);
    Copy(message10_.message[i], message10_.other_message[i]);
    Reflection(message6_.message[i]);
    Merge(message9_.message[i], message9_.other_message[i]);
    Copy(message19_.message[i], message19_.other_message[i]);
    Copy(message12_.message[i], message12_.other_message[i]);
    SpaceUsed(message19_.message[i]);
    Descriptor(message19_.message[i]);
    Reflection(message10_.message[i]);
    Reflection(message19_.message[i]);
    Copy(message17_.message[i], message17_.other_message[i]);
    Deserialize(message14_.other_message[i], &message14_.string[i]);
    Deserialize(message15_.message[i], &message15_.string[i]);
    Reflection(message8_.message[i]);
    Copy(message19_.message[i], message19_.other_message[i]);
    Reflection(message12_.message[i]);
    Serialize(message1_.other_message[i], &message1_.string[i]);
    Descriptor(message9_.message[i]);
    Destroy(message2_.other_message[i]);
    message2_.other_message[i] = google::protobuf::Arena::Create<Message2>(arena_);
    Message2_Set_2(message2_.other_message[i], &s_);
    Message6_Get_3(message6_.message[i]);
    Reflection(message3_.message[i]);
    Copy(message15_.message[i], message15_.other_message[i]);
    ByteSize(message5_.message[i]);
    Reflection(message11_.message[i]);
    Copy(message13_.message[i], message13_.other_message[i]);
    Serialize(message14_.other_message[i], &message14_.string[i]);
    Copy(message13_.message[i], message13_.other_message[i]);
    ByteSize(message11_.message[i]);
    Copy(message14_.message[i], message14_.other_message[i]);
    Copy(message1_.message[i], message1_.other_message[i]);
    Descriptor(message15_.message[i]);
    Message16_Set_3(message16_.other_message[i], &s_);
    Destroy(message4_.other_message[i]);
    message4_.other_message[i] = google::protobuf::Arena::Create<Message4>(arena_);
    Message4_Set_2(message4_.other_message[i], &s_);
    Reflection(message19_.message[i]);
    Serialize(message1_.message[i], &message1_.string[i]);
    Reflection(message13_.message[i]);
    Serialize(message19_.other_message[i], &message19_.string[i]);
    Destroy(message19_.other_message[i]);
    message19_.other_message[i] = google::protobuf::Arena::Create<Message19>(arena_);
    Message19_Set_2(message19_.other_message[i], &s_);
    Reflection(message0_.message[i]);
    Reflection(message15_.message[i]);
    Destroy(message0_.other_message[i]);
    message0_.other_message[i] = google::protobuf::Arena::Create<Message0>(arena_);
    Message0_Set_2(message0_.other_message[i], &s_);
    ByteSize(message7_.message[i]);
    Reflection(message8_.message[i]);
    ByteSize(message0_.message[i]);
    Message16_Get_1(message16_.message[i]);
    Copy(message8_.message[i], message8_.other_message[i]);
    Copy(message11_.message[i], message11_.other_message[i]);
    Reflection(message13_.message[i]);
    Destroy(message16_.message[i]);
    message16_.message[i] = google::protobuf::Arena::Create<Message16>(arena_);
    Message16_Set_2(message16_.message[i], &s_);
    Copy(message0_.message[i], message0_.other_message[i]);
    Copy(message7_.message[i], message7_.other_message[i]);
    Reflection(message6_.message[i]);
    Descriptor(message14_.message[i]);
    Destroy(message7_.message[i]);
    message7_.message[i] = google::protobuf::Arena::Create<Message7>(arena_);
    Message7_Set_2(message7_.message[i], &s_);
    Message6_Get_4(message6_.message[i]);
    Reflection(message3_.message[i]);
    Reflection(message1_.message[i]);
    Descriptor(message6_.message[i]);
    Message15_Set_2(message15_.message[i], &s_);
    Reflection(message18_.message[i]);
    Descriptor(message8_.message[i]);
    Copy(message16_.message[i], message16_.other_message[i]);
    Reflection(message8_.message[i]);
    Reflection(message1_.message[i]);
    Reflection(message17_.message[i]);
    ByteSize(message13_.message[i]);
    Reflection(message19_.message[i]);
    Copy(message12_.message[i], message12_.other_message[i]);
    Destroy(message1_.message[i]);
    message1_.message[i] = google::protobuf::Arena::Create<Message1>(arena_);
    Message1_Set_2(message1_.message[i], &s_);
    Reflection(message8_.message[i]);
    Destroy(message11_.other_message[i]);
    message11_.other_message[i] = google::protobuf::Arena::Create<Message11>(arena_);
    Message11_Set_2(message11_.other_message[i], &s_);
    Destroy(message17_.message[i]);
    message17_.message[i] = google::protobuf::Arena::Create<Message17>(arena_);
    Message17_Set_2(message17_.message[i], &s_);
    Serialize(message2_.message[i], &message2_.string[i]);
    Reflection(message12_.message[i]);
    Copy(message8_.message[i], message8_.other_message[i]);
    Swap(message14_.message[i], message14_.other_message[i]);
    ByteSize(message5_.message[i]);
    Reflection(message15_.message[i]);
    Reflection(message8_.message[i]);
    Copy(message11_.message[i], message11_.other_message[i]);
    Message0_Get_3(message0_.message[i]);
    SpaceUsed(message18_.message[i]);
    Message11_Set_3(message11_.other_message[i], &s_);
    Destroy(message15_.message[i]);
    message15_.message[i] = google::protobuf::Arena::Create<Message15>(arena_);
    Message15_Set_2(message15_.message[i], &s_);
    Copy(message10_.message[i], message10_.other_message[i]);
    Copy(message12_.message[i], message12_.other_message[i]);
    Destroy(message15_.other_message[i]);
    message15_.other_message[i] = google::protobuf::Arena::Create<Message15>(arena_);
    Message15_Set_2(message15_.other_message[i], &s_);
    Message2_Set_3(message2_.other_message[i], &s_);
    Destroy(message15_.other_message[i]);
    message15_.other_message[i] = google::protobuf::Arena::Create<Message15>(arena_);
    Message15_Set_2(message15_.other_message[i], &s_);
    Copy(message5_.message[i], message5_.other_message[i]);
    Reflection(message7_.message[i]);
    Deserialize(message1_.message[i], &message1_.string[i]);
    Merge(message16_.message[i], message16_.other_message[i]);
    Merge(message19_.message[i], message19_.other_message[i]);
    Serialize(message2_.message[i], &message2_.string[i]);
    Reflection(message18_.message[i]);
    Swap(message6_.message[i], message6_.other_message[i]);
    Message9_Set_3(message9_.message[i], &s_);
    Message8_Get_1(message8_.message[i]);
    Copy(message0_.message[i], message0_.other_message[i]);
    ByteSize(message19_.message[i]);
    Serialize(message14_.other_message[i], &message14_.string[i]);
    Destroy(message9_.other_message[i]);
    message9_.other_message[i] = google::protobuf::Arena::Create<Message9>(arena_);
    Message9_Set_2(message9_.other_message[i], &s_);
    Descriptor(message10_.message[i]);
    Copy(message1_.message[i], message1_.other_message[i]);
    Destroy(message13_.message[i]);
    message13_.message[i] = google::protobuf::Arena::Create<Message13>(arena_);
    Message13_Set_2(message13_.message[i], &s_);
    Reflection(message18_.message[i]);
    Copy(message7_.message[i], message7_.other_message[i]);
    Reflection(message12_.message[i]);
    Reflection(message7_.message[i]);
    Deserialize(message18_.other_message[i], &message18_.string[i]);
    SpaceUsed(message8_.message[i]);
    Copy(message19_.message[i], message19_.other_message[i]);
    Copy(message11_.message[i], message11_.other_message[i]);
    ByteSize(message1_.message[i]);
    Deserialize(message4_.other_message[i], &message4_.string[i]);
    ByteSize(message13_.message[i]);
    Copy(message14_.message[i], message14_.other_message[i]);
    Deserialize(message3_.message[i], &message3_.string[i]);
    Message13_Get_2(message13_.message[i]);
    Reflection(message11_.message[i]);
    Destroy(message11_.message[i]);
    message11_.message[i] = google::protobuf::Arena::Create<Message11>(arena_);
    Message11_Set_2(message11_.message[i], &s_);
    Message13_Get_3(message13_.message[i]);
    Destroy(message18_.other_message[i]);
    message18_.other_message[i] = google::protobuf::Arena::Create<Message18>(arena_);
    Message18_Set_2(message18_.other_message[i], &s_);
    Reflection(message15_.message[i]);
    Copy(message8_.message[i], message8_.other_message[i]);
    Reflection(message10_.message[i]);
    Reflection(message14_.message[i]);
    Copy(message16_.message[i], message16_.other_message[i]);
    Reflection(message5_.message[i]);
    Copy(message13_.message[i], message13_.other_message[i]);
    Reflection(message10_.message[i]);
    Reflection(message6_.message[i]);
    Destroy(message1_.message[i]);
    message1_.message[i] = google::protobuf::Arena::Create<Message1>(arena_);
    Message1_Set_2(message1_.message[i], &s_);
    Reflection(message7_.message[i]);
    Copy(message10_.message[i], message10_.other_message[i]);
    Reflection(message4_.message[i]);
    Destroy(message5_.other_message[i]);
    message5_.other_message[i] = google::protobuf::Arena::Create<Message5>(arena_);
    Message5_Set_2(message5_.other_message[i], &s_);
    Reflection(message15_.message[i]);
    Destroy(message5_.other_message[i]);
    message5_.other_message[i] = google::protobuf::Arena::Create<Message5>(arena_);
    Message5_Set_2(message5_.other_message[i], &s_);
    Reflection(message1_.message[i]);
    Copy(message0_.message[i], message0_.other_message[i]);
    Destroy(message11_.other_message[i]);
    message11_.other_message[i] = google::protobuf::Arena::Create<Message11>(arena_);
    Message11_Set_2(message11_.other_message[i], &s_);
    Copy(message14_.message[i], message14_.other_message[i]);
    Swap(message6_.message[i], message6_.other_message[i]);
    Reflection(message13_.message[i]);
    Descriptor(message9_.message[i]);
    Reflection(message6_.message[i]);
    Destroy(message7_.other_message[i]);
    message7_.other_message[i] = google::protobuf::Arena::Create<Message7>(arena_);
    Message7_Set_2(message7_.other_message[i], &s_);
    Reflection(message2_.message[i]);
    Reflection(message10_.message[i]);
    Reflection(message13_.message[i]);
    Reflection(message5_.message[i]);
    Destroy(message3_.message[i]);
    message3_.message[i] = google::protobuf::Arena::Create<Message3>(arena_);
    Message3_Set_2(message3_.message[i], &s_);
    Copy(message6_.message[i], message6_.other_message[i]);
    Serialize(message0_.message[i], &message0_.string[i]);
    ByteSize(message6_.message[i]);
    ByteSize(message9_.message[i]);
    Reflection(message4_.message[i]);
    Reflection(message17_.message[i]);
    Destroy(message8_.message[i]);
    message8_.message[i] = google::protobuf::Arena::Create<Message8>(arena_);
    Message8_Set_2(message8_.message[i], &s_);
    ByteSize(message16_.message[i]);
    Deserialize(message16_.message[i], &message16_.string[i]);
    Reflection(message14_.message[i]);
    Reflection(message0_.message[i]);
    Descriptor(message2_.message[i]);
    Message1_Set_3(message1_.other_message[i], &s_);
    Copy(message17_.message[i], message17_.other_message[i]);
    Copy(message17_.message[i], message17_.other_message[i]);
    Copy(message7_.message[i], message7_.other_message[i]);
    Reflection(message11_.message[i]);
    Copy(message17_.message[i], message17_.other_message[i]);
    Reflection(message16_.message[i]);
    SpaceUsed(message10_.message[i]);
    Copy(message2_.message[i], message2_.other_message[i]);
    Destroy(message2_.other_message[i]);
    message2_.other_message[i] = google::protobuf::Arena::Create<Message2>(arena_);
    Message2_Set_2(message2_.other_message[i], &s_);
    ByteSize(message11_.message[i]);
    ByteSize(message3_.message[i]);
    Deserialize(message15_.other_message[i], &message15_.string[i]);
    Reflection(message8_.message[i]);
    Destroy(message15_.other_message[i]);
    message15_.other_message[i] = google::protobuf::Arena::Create<Message15>(arena_);
    Message15_Set_2(message15_.other_message[i], &s_);
    SpaceUsed(message17_.message[i]);
    Copy(message11_.message[i], message11_.other_message[i]);
    Destroy(message9_.other_message[i]);
    message9_.other_message[i] = google::protobuf::Arena::Create<Message9>(arena_);
    Message9_Set_2(message9_.other_message[i], &s_);
    Message7_Set_3(message7_.other_message[i], &s_);
    Copy(message14_.message[i], message14_.other_message[i]);
    ByteSize(message1_.message[i]);
    Copy(message11_.message[i], message11_.other_message[i]);
    Reflection(message7_.message[i]);
    Destroy(message13_.other_message[i]);
    message13_.other_message[i] = google::protobuf::Arena::Create<Message13>(arena_);
    Message13_Set_2(message13_.other_message[i], &s_);
    Message5_Get_1(message5_.message[i]);
    Reflection(message7_.message[i]);
    Copy(message11_.message[i], message11_.other_message[i]);
    Copy(message18_.message[i], message18_.other_message[i]);
    Reflection(message10_.message[i]);
    Reflection(message7_.message[i]);
    Copy(message2_.message[i], message2_.other_message[i]);
    Deserialize(message1_.message[i], &message1_.string[i]);
    Reflection(message2_.message[i]);
    Deserialize(message14_.other_message[i], &message14_.string[i]);
    Copy(message4_.message[i], message4_.other_message[i]);
    Copy(message19_.message[i], message19_.other_message[i]);
    Descriptor(message13_.message[i]);
    Copy(message0_.message[i], message0_.other_message[i]);
    Descriptor(message8_.message[i]);
    Message2_Set_4(message2_.other_message[i], &s_);
    Copy(message2_.message[i], message2_.other_message[i]);
    ByteSize(message2_.message[i]);
    Reflection(message4_.message[i]);
    Message8_Get_2(message8_.message[i]);
    Message12_Set_1(message12_.other_message[i], &s_);
    Copy(message19_.message[i], message19_.other_message[i]);
    Message1_Get_2(message1_.message[i]);
    Reflection(message0_.message[i]);
    Reflection(message4_.message[i]);
    Copy(message12_.message[i], message12_.other_message[i]);
    Reflection(message3_.message[i]);
    Reflection(message6_.message[i]);
    Descriptor(message0_.message[i]);
    Message9_Get_3(message9_.message[i]);
    Reflection(message13_.message[i]);
    Copy(message2_.message[i], message2_.other_message[i]);
    Message15_Get_2(message15_.message[i]);
    Serialize(message18_.message[i], &message18_.string[i]);
    Merge(message1_.message[i], message1_.other_message[i]);
    ByteSize(message17_.message[i]);
    Descriptor(message11_.message[i]);
    Reflection(message10_.message[i]);
    Serialize(message1_.other_message[i], &message1_.string[i]);
    ByteSize(message14_.message[i]);
    Destroy(message14_.other_message[i]);
    message14_.other_message[i] = google::protobuf::Arena::Create<Message14>(arena_);
    Message14_Set_2(message14_.other_message[i], &s_);
    Reflection(message17_.message[i]);
    ByteSize(message10_.message[i]);
    Reflection(message17_.message[i]);
    Descriptor(message15_.message[i]);
    Reflection(message17_.message[i]);
    Reflection(message2_.message[i]);
    Destroy(message13_.message[i]);
    message13_.message[i] = google::protobuf::Arena::Create<Message13>(arena_);
    Message13_Set_2(message13_.message[i], &s_);
    Reflection(message1_.message[i]);
    Copy(message14_.message[i], message14_.other_message[i]);
    Copy(message15_.message[i], message15_.other_message[i]);
    Message5_Get_2(message5_.message[i]);
    Copy(message3_.message[i], message3_.other_message[i]);
    Serialize(message1_.message[i], &message1_.string[i]);
    Reflection(message14_.message[i]);
    Reflection(message3_.message[i]);
    Copy(message11_.message[i], message11_.other_message[i]);
    Copy(message14_.message[i], message14_.other_message[i]);
    Destroy(message16_.message[i]);
    message16_.message[i] = google::protobuf::Arena::Create<Message16>(arena_);
    Message16_Set_2(message16_.message[i], &s_);
    Reflection(message13_.message[i]);
    Copy(message2_.message[i], message2_.other_message[i]);
    Destroy(message4_.message[i]);
    message4_.message[i] = google::protobuf::Arena::Create<Message4>(arena_);
    Message4_Set_2(message4_.message[i], &s_);
    Reflection(message12_.message[i]);
    Copy(message2_.message[i], message2_.other_message[i]);
    Destroy(message12_.other_message[i]);
    message12_.other_message[i] = google::protobuf::Arena::Create<Message12>(arena_);
    Message12_Set_2(message12_.other_message[i], &s_);
    Reflection(message16_.message[i]);
    Descriptor(message13_.message[i]);
    Reflection(message10_.message[i]);
    Reflection(message5_.message[i]);
    Reflection(message14_.message[i]);
    Reflection(message17_.message[i]);
    Reflection(message11_.message[i]);
    Copy(message3_.message[i], message3_.other_message[i]);
    Message16_Get_2(message16_.message[i]);
    Destroy(message7_.message[i]);
    message7_.message[i] = google::protobuf::Arena::Create<Message7>(arena_);
    Message7_Set_2(message7_.message[i], &s_);
    Swap(message5_.message[i], message5_.other_message[i]);
    Copy(message4_.message[i], message4_.other_message[i]);
    Message11_Get_1(message11_.message[i]);
    ByteSize(message14_.message[i]);
    Reflection(message15_.message[i]);
    Serialize(message1_.other_message[i], &message1_.string[i]);
    Copy(message1_.message[i], message1_.other_message[i]);
    Message15_Get_3(message15_.message[i]);
    Serialize(message3_.other_message[i], &message3_.string[i]);
    Reflection(message5_.message[i]);
    Serialize(message14_.message[i], &message14_.string[i]);
    Reflection(message8_.message[i]);
    Message15_Get_4(message15_.message[i]);
    Copy(message16_.message[i], message16_.other_message[i]);
    ByteSize(message6_.message[i]);
    Destroy(message9_.other_message[i]);
    message9_.other_message[i] = google::protobuf::Arena::Create<Message9>(arena_);
    Message9_Set_2(message9_.other_message[i], &s_);
    Copy(message0_.message[i], message0_.other_message[i]);
    Reflection(message3_.message[i]);
    Deserialize(message4_.message[i], &message4_.string[i]);
    Message10_Set_3(message10_.message[i], &s_);
    Copy(message5_.message[i], message5_.other_message[i]);
    Reflection(message14_.message[i]);
    Reflection(message6_.message[i]);
    ByteSize(message16_.message[i]);
    Message17_Set_2(message17_.other_message[i], &s_);
    Message18_Set_4(message18_.other_message[i], &s_);
    Deserialize(message12_.other_message[i], &message12_.string[i]);
    Copy(message9_.message[i], message9_.other_message[i]);
    Reflection(message0_.message[i]);
    Reflection(message10_.message[i]);
    Serialize(message4_.other_message[i], &message4_.string[i]);
    Deserialize(message6_.message[i], &message6_.string[i]);
    Reflection(message6_.message[i]);
    Serialize(message9_.message[i], &message9_.string[i]);
    Destroy(message14_.other_message[i]);
    message14_.other_message[i] = google::protobuf::Arena::Create<Message14>(arena_);
    Message14_Set_2(message14_.other_message[i], &s_);
    Descriptor(message2_.message[i]);
    Copy(message7_.message[i], message7_.other_message[i]);
    Reflection(message13_.message[i]);
    Copy(message12_.message[i], message12_.other_message[i]);
    Reflection(message11_.message[i]);
    Message11_Set_4(message11_.message[i], &s_);
    Copy(message7_.message[i], message7_.other_message[i]);
    Serialize(message6_.other_message[i], &message6_.string[i]);
    Copy(message16_.message[i], message16_.other_message[i]);
    Copy(message11_.message[i], message11_.other_message[i]);
    Copy(message11_.message[i], message11_.other_message[i]);
    Serialize(message9_.message[i], &message9_.string[i]);
    Reflection(message3_.message[i]);
    Copy(message10_.message[i], message10_.other_message[i]);
    SpaceUsed(message12_.message[i]);
    Reflection(message17_.message[i]);
    Descriptor(message16_.message[i]);
    Copy(message13_.message[i], message13_.other_message[i]);
    Reflection(message14_.message[i]);
    Merge(message17_.message[i], message17_.other_message[i]);
    Reflection(message12_.message[i]);
    Reflection(message11_.message[i]);
    Message3_Set_3(message3_.message[i], &s_);
    Destroy(message17_.message[i]);
    message17_.message[i] = google::protobuf::Arena::Create<Message17>(arena_);
    Message17_Set_2(message17_.message[i], &s_);
    Reflection(message6_.message[i]);
    Reflection(message2_.message[i]);
    Reflection(message2_.message[i]);
    Deserialize(message19_.message[i], &message19_.string[i]);
    Message1_Get_3(message1_.message[i]);
    Copy(message16_.message[i], message16_.other_message[i]);
    Copy(message14_.message[i], message14_.other_message[i]);
    Deserialize(message16_.other_message[i], &message16_.string[i]);
    ByteSize(message5_.message[i]);
    Copy(message15_.message[i], message15_.other_message[i]);
    Reflection(message5_.message[i]);
    Swap(message15_.message[i], message15_.other_message[i]);
    Swap(message1_.message[i], message1_.other_message[i]);
    Serialize(message15_.message[i], &message15_.string[i]);
    Reflection(message6_.message[i]);
    Copy(message7_.message[i], message7_.other_message[i]);
    Copy(message13_.message[i], message13_.other_message[i]);
    ByteSize(message19_.message[i]);
    Reflection(message17_.message[i]);
    Message19_Set_3(message19_.other_message[i], &s_);
    Copy(message10_.message[i], message10_.other_message[i]);
    Reflection(message8_.message[i]);
    Reflection(message2_.message[i]);
    Reflection(message9_.message[i]);
    Destroy(message1_.other_message[i]);
    message1_.other_message[i] = google::protobuf::Arena::Create<Message1>(arena_);
    Message1_Set_2(message1_.other_message[i], &s_);
    Copy(message17_.message[i], message17_.other_message[i]);
    Deserialize(message7_.other_message[i], &message7_.string[i]);
    Reflection(message19_.message[i]);
    Copy(message2_.message[i], message2_.other_message[i]);
    Reflection(message19_.message[i]);
    Descriptor(message9_.message[i]);
    Message2_Get_1(message2_.message[i]);
    Serialize(message15_.message[i], &message15_.string[i]);
    Swap(message7_.message[i], message7_.other_message[i]);
    Destroy(message17_.other_message[i]);
    message17_.other_message[i] = google::protobuf::Arena::Create<Message17>(arena_);
    Message17_Set_2(message17_.other_message[i], &s_);
    Reflection(message0_.message[i]);
    Copy(message9_.message[i], message9_.other_message[i]);
    Reflection(message8_.message[i]);
    Serialize(message5_.other_message[i], &message5_.string[i]);
    Copy(message3_.message[i], message3_.other_message[i]);
    Destroy(message12_.other_message[i]);
    message12_.other_message[i] = google::protobuf::Arena::Create<Message12>(arena_);
    Message12_Set_2(message12_.other_message[i], &s_);
    Descriptor(message17_.message[i]);
    Copy(message9_.message[i], message9_.other_message[i]);
    Serialize(message13_.message[i], &message13_.string[i]);
    Destroy(message13_.other_message[i]);
    message13_.other_message[i] = google::protobuf::Arena::Create<Message13>(arena_);
    Message13_Set_2(message13_.other_message[i], &s_);
    Reflection(message8_.message[i]);
    Reflection(message0_.message[i]);
    Copy(message18_.message[i], message18_.other_message[i]);
    Destroy(message4_.other_message[i]);
    message4_.other_message[i] = google::protobuf::Arena::Create<Message4>(arena_);
    Message4_Set_2(message4_.other_message[i], &s_);
    Copy(message17_.message[i], message17_.other_message[i]);
    Destroy(message2_.message[i]);
    message2_.message[i] = google::protobuf::Arena::Create<Message2>(arena_);
    Message2_Set_2(message2_.message[i], &s_);
    Message6_Set_3(message6_.other_message[i], &s_);
    Deserialize(message12_.other_message[i], &message12_.string[i]);
    Copy(message8_.message[i], message8_.other_message[i]);
    Merge(message7_.message[i], message7_.other_message[i]);
    Destroy(message19_.other_message[i]);
    message19_.other_message[i] = google::protobuf::Arena::Create<Message19>(arena_);
    Message19_Set_2(message19_.other_message[i], &s_);
    ByteSize(message16_.message[i]);
    Message17_Get_1(message17_.message[i]);
    Reflection(message18_.message[i]);
    ByteSize(message17_.message[i]);
    Reflection(message18_.message[i]);
    Destroy(message18_.other_message[i]);
    message18_.other_message[i] = google::protobuf::Arena::Create<Message18>(arena_);
    Message18_Set_2(message18_.other_message[i], &s_);
    Reflection(message1_.message[i]);
    Reflection(message17_.message[i]);
    Copy(message8_.message[i], message8_.other_message[i]);
    Destroy(message0_.message[i]);
    message0_.message[i] = google::protobuf::Arena::Create<Message0>(arena_);
    Message0_Set_2(message0_.message[i], &s_);
    Deserialize(message17_.message[i], &message17_.string[i]);
    Reflection(message14_.message[i]);
    Reflection(message19_.message[i]);
    ByteSize(message17_.message[i]);
    SpaceUsed(message1_.message[i]);
    Copy(message18_.message[i], message18_.other_message[i]);
    Copy(message11_.message[i], message11_.other_message[i]);
    ByteSize(message8_.message[i]);
    Message10_Set_4(message10_.message[i], &s_);
    Reflection(message6_.message[i]);
    Copy(message6_.message[i], message6_.other_message[i]);
    Message17_Get_2(message17_.message[i]);
    Reflection(message10_.message[i]);
    Reflection(message4_.message[i]);
    Copy(message6_.message[i], message6_.other_message[i]);
    Message15_Get_1(message15_.message[i]);
    Copy(message15_.message[i], message15_.other_message[i]);
    ByteSize(message17_.message[i]);
    Reflection(message11_.message[i]);
    Copy(message11_.message[i], message11_.other_message[i]);
    Reflection(message7_.message[i]);
    Reflection(message15_.message[i]);
    Reflection(message15_.message[i]);
    Copy(message14_.message[i], message14_.other_message[i]);
    Copy(message6_.message[i], message6_.other_message[i]);
    Message17_Set_3(message17_.message[i], &s_);
    ByteSize(message12_.message[i]);
    Reflection(message8_.message[i]);
    Deserialize(message11_.message[i], &message11_.string[i]);
    Descriptor(message13_.message[i]);
    Reflection(message8_.message[i]);
    Reflection(message15_.message[i]);
    Reflection(message13_.message[i]);
    Reflection(message5_.message[i]);
    Reflection(message18_.message[i]);
    Deserialize(message15_.message[i], &message15_.string[i]);
    Serialize(message1_.message[i], &message1_.string[i]);
    Message16_Get_3(message16_.message[i]);
    Destroy(message16_.message[i]);
    message16_.message[i] = google::protobuf::Arena::Create<Message16>(arena_);
    Message16_Set_2(message16_.message[i], &s_);
    Copy(message6_.message[i], message6_.other_message[i]);
    Copy(message15_.message[i], message15_.other_message[i]);
    Copy(message9_.message[i], message9_.other_message[i]);
    Reflection(message6_.message[i]);
    Copy(message1_.message[i], message1_.other_message[i]);
    Merge(message4_.message[i], message4_.other_message[i]);
    Reflection(message7_.message[i]);
    Destroy(message8_.other_message[i]);
    message8_.other_message[i] = google::protobuf::Arena::Create<Message8>(arena_);
    Message8_Set_2(message8_.other_message[i], &s_);
    Descriptor(message17_.message[i]);
    Reflection(message11_.message[i]);
    Copy(message17_.message[i], message17_.other_message[i]);
    Destroy(message17_.message[i]);
    message17_.message[i] = google::protobuf::Arena::Create<Message17>(arena_);
    Message17_Set_2(message17_.message[i], &s_);
    Message6_Get_1(message6_.message[i]);
    Reflection(message6_.message[i]);
    Serialize(message0_.message[i], &message0_.string[i]);
    Descriptor(message7_.message[i]);
    Copy(message15_.message[i], message15_.other_message[i]);
    Serialize(message7_.other_message[i], &message7_.string[i]);
    Reflection(message13_.message[i]);
    Reflection(message1_.message[i]);
    Reflection(message8_.message[i]);
    ByteSize(message9_.message[i]);
    Reflection(message8_.message[i]);
    Message5_Get_3(message5_.message[i]);
    Deserialize(message19_.other_message[i], &message19_.string[i]);
    Copy(message19_.message[i], message19_.other_message[i]);
    Deserialize(message12_.other_message[i], &message12_.string[i]);
    Message2_Get_2(message2_.message[i]);
    Message7_Set_4(message7_.message[i], &s_);
    Copy(message0_.message[i], message0_.other_message[i]);
    Reflection(message16_.message[i]);
    Destroy(message9_.other_message[i]);
    message9_.other_message[i] = google::protobuf::Arena::Create<Message9>(arena_);
    Message9_Set_2(message9_.other_message[i], &s_);
    Reflection(message12_.message[i]);
    ByteSize(message12_.message[i]);
    Reflection(message5_.message[i]);
    Reflection(message5_.message[i]);
    Reflection(message15_.message[i]);
    Deserialize(message15_.other_message[i], &message15_.string[i]);
    Copy(message12_.message[i], message12_.other_message[i]);
    Copy(message9_.message[i], message9_.other_message[i]);
    Reflection(message17_.message[i]);
    Serialize(message11_.message[i], &message11_.string[i]);
    ByteSize(message4_.message[i]);
    Message6_Set_4(message6_.message[i], &s_);
    Message0_Get_4(message0_.message[i]);
    Reflection(message15_.message[i]);
    Copy(message13_.message[i], message13_.other_message[i]);
    Copy(message7_.message[i], message7_.other_message[i]);
    Reflection(message11_.message[i]);
    Copy(message2_.message[i], message2_.other_message[i]);
    ByteSize(message8_.message[i]);
    Message17_Get_3(message17_.message[i]);
    SpaceUsed(message19_.message[i]);
    Deserialize(message18_.other_message[i], &message18_.string[i]);
    Copy(message15_.message[i], message15_.other_message[i]);
    Descriptor(message16_.message[i]);
    Reflection(message3_.message[i]);
    Reflection(message6_.message[i]);
    Serialize(message6_.other_message[i], &message6_.string[i]);
    Copy(message16_.message[i], message16_.other_message[i]);
    SpaceUsed(message1_.message[i]);
    Serialize(message18_.message[i], &message18_.string[i]);
    Deserialize(message17_.message[i], &message17_.string[i]);
    Reflection(message14_.message[i]);
    Copy(message18_.message[i], message18_.other_message[i]);
    Copy(message11_.message[i], message11_.other_message[i]);
    Reflection(message8_.message[i]);
    Reflection(message2_.message[i]);
    Reflection(message17_.message[i]);
    Destroy(message10_.message[i]);
    message10_.message[i] = google::protobuf::Arena::Create<Message10>(arena_);
    Message10_Set_2(message10_.message[i], &s_);
    Reflection(message16_.message[i]);
    Merge(message11_.message[i], message11_.other_message[i]);
    SpaceUsed(message14_.message[i]);
    Reflection(message0_.message[i]);
    Destroy(message5_.message[i]);
    message5_.message[i] = google::protobuf::Arena::Create<Message5>(arena_);
    Message5_Set_2(message5_.message[i], &s_);
    Copy(message0_.message[i], message0_.other_message[i]);
    Destroy(message11_.other_message[i]);
    message11_.other_message[i] = google::protobuf::Arena::Create<Message11>(arena_);
    Message11_Set_2(message11_.other_message[i], &s_);
    Reflection(message9_.message[i]);
    Copy(message18_.message[i], message18_.other_message[i]);
    Reflection(message0_.message[i]);
    ByteSize(message1_.message[i]);
    Message9_Set_4(message9_.other_message[i], &s_);
    Reflection(message15_.message[i]);
    Copy(message5_.message[i], message5_.other_message[i]);
    Destroy(message6_.message[i]);
    message6_.message[i] = google::protobuf::Arena::Create<Message6>(arena_);
    Message6_Set_2(message6_.message[i], &s_);
    Message9_Set_1(message9_.message[i], &s_);
    Message17_Set_4(message17_.message[i], &s_);
    Reflection(message13_.message[i]);
    Descriptor(message11_.message[i]);
    Copy(message4_.message[i], message4_.other_message[i]);
    Destroy(message16_.other_message[i]);
    message16_.other_message[i] = google::protobuf::Arena::Create<Message16>(arena_);
    Message16_Set_2(message16_.other_message[i], &s_);
    Reflection(message12_.message[i]);
    Reflection(message3_.message[i]);
    Reflection(message18_.message[i]);
    Copy(message15_.message[i], message15_.other_message[i]);
    Reflection(message10_.message[i]);
    Reflection(message3_.message[i]);
    ByteSize(message4_.message[i]);
    Destroy(message13_.message[i]);
    message13_.message[i] = google::protobuf::Arena::Create<Message13>(arena_);
    Message13_Set_2(message13_.message[i], &s_);
    Descriptor(message14_.message[i]);
    Copy(message16_.message[i], message16_.other_message[i]);
    SpaceUsed(message1_.message[i]);
    SpaceUsed(message17_.message[i]);
    SpaceUsed(message6_.message[i]);
    Serialize(message0_.other_message[i], &message0_.string[i]);
    Reflection(message1_.message[i]);
    Message11_Set_1(message11_.message[i], &s_);
    ByteSize(message5_.message[i]);
    Copy(message4_.message[i], message4_.other_message[i]);
    Reflection(message9_.message[i]);
    Copy(message4_.message[i], message4_.other_message[i]);
    Serialize(message19_.message[i], &message19_.string[i]);
    Descriptor(message19_.message[i]);
    Deserialize(message13_.other_message[i], &message13_.string[i]);
    Message4_Get_1(message4_.message[i]);
    Deserialize(message19_.other_message[i], &message19_.string[i]);
    Deserialize(message4_.other_message[i], &message4_.string[i]);
    Reflection(message19_.message[i]);
    Reflection(message5_.message[i]);
    SpaceUsed(message1_.message[i]);
    ByteSize(message10_.message[i]);
    Serialize(message14_.message[i], &message14_.string[i]);
    Descriptor(message10_.message[i]);
    Destroy(message10_.message[i]);
    message10_.message[i] = google::protobuf::Arena::Create<Message10>(arena_);
    Message10_Set_2(message10_.message[i], &s_);
    Copy(message7_.message[i], message7_.other_message[i]);
    Copy(message12_.message[i], message12_.other_message[i]);
    Reflection(message0_.message[i]);
    ByteSize(message18_.message[i]);
    Reflection(message0_.message[i]);
    SpaceUsed(message15_.message[i]);
    Destroy(message2_.message[i]);
    message2_.message[i] = google::protobuf::Arena::Create<Message2>(arena_);
    Message2_Set_2(message2_.message[i], &s_);
    Reflection(message6_.message[i]);
    ByteSize(message6_.message[i]);
    Message0_Set_4(message0_.other_message[i], &s_);
    Copy(message2_.message[i], message2_.other_message[i]);
    Message18_Get_3(message18_.message[i]);
    Reflection(message9_.message[i]);
    Deserialize(message8_.other_message[i], &message8_.string[i]);
    SpaceUsed(message17_.message[i]);
    Deserialize(message15_.message[i], &message15_.string[i]);
    Reflection(message16_.message[i]);
    Destroy(message13_.other_message[i]);
    message13_.other_message[i] = google::protobuf::Arena::Create<Message13>(arena_);
    Message13_Set_2(message13_.other_message[i], &s_);
    Copy(message19_.message[i], message19_.other_message[i]);
    Deserialize(message18_.other_message[i], &message18_.string[i]);
    ByteSize(message3_.message[i]);
    SpaceUsed(message16_.message[i]);
    Reflection(message3_.message[i]);
    Reflection(message4_.message[i]);
    Destroy(message16_.other_message[i]);
    message16_.other_message[i] = google::protobuf::Arena::Create<Message16>(arena_);
    Message16_Set_2(message16_.other_message[i], &s_);
    Descriptor(message12_.message[i]);
    Message4_Get_2(message4_.message[i]);
    Reflection(message14_.message[i]);
    Copy(message16_.message[i], message16_.other_message[i]);
    Reflection(message2_.message[i]);
    Deserialize(message4_.other_message[i], &message4_.string[i]);
    Reflection(message9_.message[i]);
    Message12_Get_1(message12_.message[i]);
    Copy(message15_.message[i], message15_.other_message[i]);
    Reflection(message13_.message[i]);
    Message7_Get_3(message7_.message[i]);
    Reflection(message0_.message[i]);
    Swap(message13_.message[i], message13_.other_message[i]);
    Destroy(message1_.message[i]);
    message1_.message[i] = google::protobuf::Arena::Create<Message1>(arena_);
    Message1_Set_2(message1_.message[i], &s_);
    Reflection(message9_.message[i]);
    Serialize(message18_.other_message[i], &message18_.string[i]);
    Destroy(message7_.other_message[i]);
    message7_.other_message[i] = google::protobuf::Arena::Create<Message7>(arena_);
    Message7_Set_2(message7_.other_message[i], &s_);
    Destroy(message19_.message[i]);
    message19_.message[i] = google::protobuf::Arena::Create<Message19>(arena_);
    Message19_Set_2(message19_.message[i], &s_);
    ByteSize(message3_.message[i]);
    Destroy(message9_.other_message[i]);
    message9_.other_message[i] = google::protobuf::Arena::Create<Message9>(arena_);
    Message9_Set_2(message9_.other_message[i], &s_);
    Copy(message14_.message[i], message14_.other_message[i]);
    Descriptor(message13_.message[i]);
    Serialize(message17_.other_message[i], &message17_.string[i]);
    Reflection(message12_.message[i]);
    Reflection(message10_.message[i]);
    Deserialize(message5_.other_message[i], &message5_.string[i]);
    Reflection(message16_.message[i]);
    Descriptor(message2_.message[i]);
    Copy(message4_.message[i], message4_.other_message[i]);
    Deserialize(message12_.message[i], &message12_.string[i]);
    Reflection(message15_.message[i]);
    Reflection(message10_.message[i]);
    Reflection(message5_.message[i]);
    Reflection(message9_.message[i]);
    Descriptor(message15_.message[i]);
    Reflection(message13_.message[i]);
    Message16_Set_4(message16_.other_message[i], &s_);
    Reflection(message3_.message[i]);
    Copy(message5_.message[i], message5_.other_message[i]);
    Reflection(message12_.message[i]);
    Deserialize(message2_.message[i], &message2_.string[i]);
    Destroy(message19_.other_message[i]);
    message19_.other_message[i] = google::protobuf::Arena::Create<Message19>(arena_);
    Message19_Set_2(message19_.other_message[i], &s_);
    Descriptor(message4_.message[i]);
    ByteSize(message14_.message[i]);
    Serialize(message11_.message[i], &message11_.string[i]);
    Copy(message7_.message[i], message7_.other_message[i]);
    Descriptor(message17_.message[i]);
    Copy(message6_.message[i], message6_.other_message[i]);
    Deserialize(message6_.message[i], &message6_.string[i]);
    Swap(message1_.message[i], message1_.other_message[i]);
    Message5_Set_1(message5_.other_message[i], &s_);
    Reflection(message1_.message[i]);
    Copy(message8_.message[i], message8_.other_message[i]);
    Reflection(message13_.message[i]);
    Reflection(message17_.message[i]);
    Copy(message8_.message[i], message8_.other_message[i]);
    Reflection(message14_.message[i]);
    Serialize(message7_.other_message[i], &message7_.string[i]);
    Copy(message14_.message[i], message14_.other_message[i]);
    Reflection(message1_.message[i]);
    Reflection(message19_.message[i]);
    Reflection(message5_.message[i]);
    Destroy(message9_.message[i]);
    message9_.message[i] = google::protobuf::Arena::Create<Message9>(arena_);
    Message9_Set_2(message9_.message[i], &s_);
    ByteSize(message6_.message[i]);
    Copy(message10_.message[i], message10_.other_message[i]);
    Descriptor(message8_.message[i]);
    Descriptor(message10_.message[i]);
    Descriptor(message15_.message[i]);
    Reflection(message2_.message[i]);
    Destroy(message2_.message[i]);
    message2_.message[i] = google::protobuf::Arena::Create<Message2>(arena_);
    Message2_Set_2(message2_.message[i], &s_);
    Descriptor(message1_.message[i]);
    Message16_Get_4(message16_.message[i]);
    Copy(message2_.message[i], message2_.other_message[i]);
    Message18_Get_4(message18_.message[i]);
    SpaceUsed(message17_.message[i]);
    Reflection(message1_.message[i]);
    SpaceUsed(message11_.message[i]);
    Copy(message13_.message[i], message13_.other_message[i]);
    Descriptor(message17_.message[i]);
    ByteSize(message9_.message[i]);
    Reflection(message3_.message[i]);
    Deserialize(message16_.message[i], &message16_.string[i]);
    Swap(message11_.message[i], message11_.other_message[i]);
    Reflection(message14_.message[i]);
    Reflection(message0_.message[i]);
    Swap(message0_.message[i], message0_.other_message[i]);
    Reflection(message1_.message[i]);
    Copy(message14_.message[i], message14_.other_message[i]);
    Deserialize(message17_.other_message[i], &message17_.string[i]);
    ByteSize(message2_.message[i]);
    ByteSize(message3_.message[i]);
    Message18_Get_1(message18_.message[i]);
    Destroy(message14_.other_message[i]);
    message14_.other_message[i] = google::protobuf::Arena::Create<Message14>(arena_);
    Message14_Set_2(message14_.other_message[i], &s_);
    Copy(message6_.message[i], message6_.other_message[i]);
    Reflection(message14_.message[i]);
    Reflection(message19_.message[i]);
    Descriptor(message10_.message[i]);
    Copy(message19_.message[i], message19_.other_message[i]);
    Message18_Set_1(message18_.other_message[i], &s_);
    Message0_Set_1(message0_.message[i], &s_);
    Reflection(message9_.message[i]);
    Copy(message9_.message[i], message9_.other_message[i]);
    Merge(message6_.message[i], message6_.other_message[i]);
    Destroy(message10_.message[i]);
    message10_.message[i] = google::protobuf::Arena::Create<Message10>(arena_);
    Message10_Set_2(message10_.message[i], &s_);
    Reflection(message17_.message[i]);
    Destroy(message4_.message[i]);
    message4_.message[i] = google::protobuf::Arena::Create<Message4>(arena_);
    Message4_Set_2(message4_.message[i], &s_);
    Destroy(message12_.other_message[i]);
    message12_.other_message[i] = google::protobuf::Arena::Create<Message12>(arena_);
    Message12_Set_2(message12_.other_message[i], &s_);
    Reflection(message9_.message[i]);
    Reflection(message15_.message[i]);
    Copy(message9_.message[i], message9_.other_message[i]);
    Reflection(message16_.message[i]);
    Deserialize(message1_.message[i], &message1_.string[i]);
    Copy(message7_.message[i], message7_.other_message[i]);
    Destroy(message7_.other_message[i]);
    message7_.other_message[i] = google::protobuf::Arena::Create<Message7>(arena_);
    Message7_Set_2(message7_.other_message[i], &s_);
    Reflection(message0_.message[i]);
    Destroy(message15_.message[i]);
    Destroy(message15_.other_message[i]);
    Copy(message3_.message[i], message3_.other_message[i]);
    Copy(message2_.message[i], message2_.other_message[i]);
    Destroy(message11_.message[i]);
    Destroy(message11_.other_message[i]);
    ByteSize(message6_.message[i]);
    Copy(message6_.message[i], message6_.other_message[i]);
    Reflection(message17_.message[i]);
    Reflection(message4_.message[i]);
    Reflection(message12_.message[i]);
    Reflection(message10_.message[i]);
    Copy(message5_.message[i], message5_.other_message[i]);
    Copy(message4_.message[i], message4_.other_message[i]);
    Merge(message6_.message[i], message6_.other_message[i]);
    Reflection(message3_.message[i]);
    Reflection(message4_.message[i]);
    Reflection(message13_.message[i]);
    Copy(message7_.message[i], message7_.other_message[i]);
    Reflection(message6_.message[i]);
    Destroy(message14_.other_message[i]);
    message14_.other_message[i] = google::protobuf::Arena::Create<Message14>(arena_);
    Message14_Set_2(message14_.other_message[i], &s_);
    Deserialize(message18_.message[i], &message18_.string[i]);
    Destroy(message9_.message[i]);
    message9_.message[i] = google::protobuf::Arena::Create<Message9>(arena_);
    Message9_Set_2(message9_.message[i], &s_);
    Reflection(message0_.message[i]);
    Deserialize(message6_.other_message[i], &message6_.string[i]);
    Reflection(message6_.message[i]);
    Destroy(message8_.message[i]);
    message8_.message[i] = google::protobuf::Arena::Create<Message8>(arena_);
    Message8_Set_2(message8_.message[i], &s_);
    Deserialize(message10_.message[i], &message10_.string[i]);
    Copy(message0_.message[i], message0_.other_message[i]);
    Message9_Get_4(message9_.message[i]);
    ByteSize(message14_.message[i]);
    Message8_Set_2(message8_.other_message[i], &s_);
    ByteSize(message6_.message[i]);
    Reflection(message13_.message[i]);
    Copy(message14_.message[i], message14_.other_message[i]);
    Reflection(message18_.message[i]);
    Merge(message14_.message[i], message14_.other_message[i]);
    Reflection(message16_.message[i]);
    Message13_Set_2(message13_.other_message[i], &s_);
    Reflection(message9_.message[i]);
    Serialize(message10_.other_message[i], &message10_.string[i]);
    Message17_Get_4(message17_.message[i]);
    Reflection(message0_.message[i]);
    Reflection(message16_.message[i]);
    Destroy(message1_.other_message[i]);
    message1_.other_message[i] = google::protobuf::Arena::Create<Message1>(arena_);
    Message1_Set_2(message1_.other_message[i], &s_);
    Copy(message12_.message[i], message12_.other_message[i]);
    Copy(message10_.message[i], message10_.other_message[i]);
    Copy(message8_.message[i], message8_.other_message[i]);
    Merge(message16_.message[i], message16_.other_message[i]);
    Descriptor(message0_.message[i]);
    Reflection(message0_.message[i]);
    Serialize(message9_.other_message[i], &message9_.string[i]);
    Deserialize(message10_.message[i], &message10_.string[i]);
    Reflection(message18_.message[i]);
    Destroy(message13_.message[i]);
    Destroy(message13_.other_message[i]);
    Reflection(message2_.message[i]);
    Reflection(message14_.message[i]);
    Reflection(message5_.message[i]);
    Serialize(message3_.message[i], &message3_.string[i]);
    Reflection(message1_.message[i]);
    Reflection(message5_.message[i]);
    Reflection(message2_.message[i]);
    Destroy(message16_.message[i]);
    message16_.message[i] = google::protobuf::Arena::Create<Message16>(arena_);
    Message16_Set_2(message16_.message[i], &s_);
    Copy(message5_.message[i], message5_.other_message[i]);
    Copy(message2_.message[i], message2_.other_message[i]);
    Message17_Set_1(message17_.other_message[i], &s_);
    Copy(message4_.message[i], message4_.other_message[i]);
    Copy(message7_.message[i], message7_.other_message[i]);
    Message0_Get_1(message0_.message[i]);
    ByteSize(message3_.message[i]);
    Swap(message6_.message[i], message6_.other_message[i]);
    Reflection(message2_.message[i]);
    Destroy(message6_.message[i]);
    message6_.message[i] = google::protobuf::Arena::Create<Message6>(arena_);
    Message6_Set_2(message6_.message[i], &s_);
    Serialize(message16_.other_message[i], &message16_.string[i]);
    Destroy(message12_.other_message[i]);
    message12_.other_message[i] = google::protobuf::Arena::Create<Message12>(arena_);
    Message12_Set_2(message12_.other_message[i], &s_);
    Destroy(message5_.message[i]);
    message5_.message[i] = google::protobuf::Arena::Create<Message5>(arena_);
    Message5_Set_2(message5_.message[i], &s_);
    Descriptor(message7_.message[i]);
    Reflection(message6_.message[i]);
    Reflection(message12_.message[i]);
    Copy(message9_.message[i], message9_.other_message[i]);
    Copy(message18_.message[i], message18_.other_message[i]);
    Destroy(message18_.message[i]);
    message18_.message[i] = google::protobuf::Arena::Create<Message18>(arena_);
    Message18_Set_2(message18_.message[i], &s_);
    Destroy(message9_.message[i]);
    message9_.message[i] = google::protobuf::Arena::Create<Message9>(arena_);
    Message9_Set_2(message9_.message[i], &s_);
    Reflection(message9_.message[i]);
    Serialize(message16_.message[i], &message16_.string[i]);
    Message16_Set_1(message16_.other_message[i], &s_);
    Destroy(message3_.message[i]);
    message3_.message[i] = google::protobuf::Arena::Create<Message3>(arena_);
    Message3_Set_2(message3_.message[i], &s_);
    Reflection(message19_.message[i]);
    Reflection(message12_.message[i]);
    Destroy(message10_.other_message[i]);
    message10_.other_message[i] = google::protobuf::Arena::Create<Message10>(arena_);
    Message10_Set_2(message10_.other_message[i], &s_);
    Reflection(message7_.message[i]);
    Reflection(message14_.message[i]);
    Copy(message10_.message[i], message10_.other_message[i]);
    Reflection(message7_.message[i]);
    Reflection(message2_.message[i]);
    Copy(message8_.message[i], message8_.other_message[i]);
    Descriptor(message8_.message[i]);
    Swap(message18_.message[i], message18_.other_message[i]);
    Copy(message3_.message[i], message3_.other_message[i]);
    Destroy(message5_.other_message[i]);
    message5_.other_message[i] = google::protobuf::Arena::Create<Message5>(arena_);
    Message5_Set_2(message5_.other_message[i], &s_);
    Reflection(message8_.message[i]);
    Deserialize(message5_.other_message[i], &message5_.string[i]);
    Reflection(message16_.message[i]);
    Copy(message2_.message[i], message2_.other_message[i]);
    Reflection(message16_.message[i]);
    Serialize(message17_.other_message[i], &message17_.string[i]);
    Copy(message1_.message[i], message1_.other_message[i]);
    Deserialize(message6_.message[i], &message6_.string[i]);
    Destroy(message7_.message[i]);
    Destroy(message7_.other_message[i]);
    ByteSize(message1_.message[i]);
    Copy(message9_.message[i], message9_.other_message[i]);
    Reflection(message8_.message[i]);
    Reflection(message9_.message[i]);
    Destroy(message4_.other_message[i]);
    message4_.other_message[i] = google::protobuf::Arena::Create<Message4>(arena_);
    Message4_Set_2(message4_.other_message[i], &s_);
    SpaceUsed(message10_.message[i]);
    Swap(message10_.message[i], message10_.other_message[i]);
    Message14_Get_1(message14_.message[i]);
    Reflection(message6_.message[i]);
    Reflection(message18_.message[i]);
    Reflection(message12_.message[i]);
    Serialize(message17_.message[i], &message17_.string[i]);
    Copy(message19_.message[i], message19_.other_message[i]);
    ByteSize(message6_.message[i]);
    Copy(message9_.message[i], message9_.other_message[i]);
    Message4_Set_2(message4_.other_message[i], &s_);
    Copy(message0_.message[i], message0_.other_message[i]);
    Reflection(message1_.message[i]);
    Reflection(message8_.message[i]);
    Destroy(message6_.other_message[i]);
    message6_.other_message[i] = google::protobuf::Arena::Create<Message6>(arena_);
    Message6_Set_2(message6_.other_message[i], &s_);
    Copy(message10_.message[i], message10_.other_message[i]);
    Copy(message9_.message[i], message9_.other_message[i]);
    Reflection(message1_.message[i]);
    Message9_Get_1(message9_.message[i]);
    Serialize(message9_.message[i], &message9_.string[i]);
    Reflection(message4_.message[i]);
    Copy(message17_.message[i], message17_.other_message[i]);
    ByteSize(message4_.message[i]);
    Reflection(message4_.message[i]);
    Message8_Set_3(message8_.message[i], &s_);
    Reflection(message18_.message[i]);
    Descriptor(message4_.message[i]);
    Descriptor(message10_.message[i]);
    Copy(message0_.message[i], message0_.other_message[i]);
    ByteSize(message10_.message[i]);
    Destroy(message18_.other_message[i]);
    message18_.other_message[i] = google::protobuf::Arena::Create<Message18>(arena_);
    Message18_Set_2(message18_.other_message[i], &s_);
    ByteSize(message1_.message[i]);
    Copy(message2_.message[i], message2_.other_message[i]);
    ByteSize(message5_.message[i]);
    Reflection(message5_.message[i]);
    Reflection(message19_.message[i]);
    Copy(message8_.message[i], message8_.other_message[i]);
    Reflection(message3_.message[i]);
    Reflection(message8_.message[i]);
    Copy(message9_.message[i], message9_.other_message[i]);
    Reflection(message16_.message[i]);
    Copy(message8_.message[i], message8_.other_message[i]);
    ByteSize(message10_.message[i]);
    Descriptor(message18_.message[i]);
    Reflection(message9_.message[i]);
    Deserialize(message5_.message[i], &message5_.string[i]);
    Deserialize(message14_.other_message[i], &message14_.string[i]);
    Reflection(message16_.message[i]);
    Copy(message8_.message[i], message8_.other_message[i]);
    Descriptor(message9_.message[i]);
    Copy(message8_.message[i], message8_.other_message[i]);
    Destroy(message16_.message[i]);
    Destroy(message16_.other_message[i]);
    Message6_Set_1(message6_.other_message[i], &s_);
    Deserialize(message10_.message[i], &message10_.string[i]);
    Reflection(message18_.message[i]);
    Deserialize(message1_.other_message[i], &message1_.string[i]);
    Copy(message4_.message[i], message4_.other_message[i]);
    Serialize(message1_.message[i], &message1_.string[i]);
    Copy(message9_.message[i], message9_.other_message[i]);
    Deserialize(message10_.message[i], &message10_.string[i]);
    Deserialize(message5_.message[i], &message5_.string[i]);
    Copy(message0_.message[i], message0_.other_message[i]);
    Reflection(message0_.message[i]);
    Reflection(message12_.message[i]);
    Swap(message9_.message[i], message9_.other_message[i]);
    Reflection(message9_.message[i]);
    Destroy(message0_.message[i]);
    message0_.message[i] = google::protobuf::Arena::Create<Message0>(arena_);
    Message0_Set_2(message0_.message[i], &s_);
    Copy(message12_.message[i], message12_.other_message[i]);
    Message3_Set_4(message3_.message[i], &s_);
    Merge(message19_.message[i], message19_.other_message[i]);
    Reflection(message2_.message[i]);
    Destroy(message9_.message[i]);
    Destroy(message9_.other_message[i]);
    Reflection(message0_.message[i]);
    Copy(message5_.message[i], message5_.other_message[i]);
    Reflection(message19_.message[i]);
    Reflection(message5_.message[i]);
    Reflection(message14_.message[i]);
    Serialize(message6_.message[i], &message6_.string[i]);
    Reflection(message18_.message[i]);
    Reflection(message6_.message[i]);
    Descriptor(message5_.message[i]);
    Reflection(message1_.message[i]);
    Copy(message17_.message[i], message17_.other_message[i]);
    Reflection(message4_.message[i]);
    Reflection(message0_.message[i]);
    Deserialize(message1_.message[i], &message1_.string[i]);
    Message19_Set_4(message19_.other_message[i], &s_);
    Reflection(message3_.message[i]);
    Reflection(message5_.message[i]);
    Copy(message4_.message[i], message4_.other_message[i]);
    Descriptor(message8_.message[i]);
    Destroy(message19_.other_message[i]);
    message19_.other_message[i] = google::protobuf::Arena::Create<Message19>(arena_);
    Message19_Set_2(message19_.other_message[i], &s_);
    Destroy(message18_.message[i]);
    message18_.message[i] = google::protobuf::Arena::Create<Message18>(arena_);
    Message18_Set_2(message18_.message[i], &s_);
    Serialize(message12_.other_message[i], &message12_.string[i]);
    Descriptor(message10_.message[i]);
    Serialize(message10_.message[i], &message10_.string[i]);
    Reflection(message1_.message[i]);
    Reflection(message14_.message[i]);
    Copy(message14_.message[i], message14_.other_message[i]);
    Reflection(message3_.message[i]);
    Destroy(message17_.other_message[i]);
    message17_.other_message[i] = google::protobuf::Arena::Create<Message17>(arena_);
    Message17_Set_2(message17_.other_message[i], &s_);
    Copy(message18_.message[i], message18_.other_message[i]);
    Copy(message14_.message[i], message14_.other_message[i]);
    Reflection(message2_.message[i]);
    Deserialize(message4_.message[i], &message4_.string[i]);
    Destroy(message8_.message[i]);
    message8_.message[i] = google::protobuf::Arena::Create<Message8>(arena_);
    Message8_Set_2(message8_.message[i], &s_);
    Message10_Get_1(message10_.message[i]);
    Deserialize(message14_.other_message[i], &message14_.string[i]);
    SpaceUsed(message10_.message[i]);
    Message10_Set_1(message10_.other_message[i], &s_);
    Reflection(message2_.message[i]);
    Copy(message12_.message[i], message12_.other_message[i]);
    Copy(message19_.message[i], message19_.other_message[i]);
    Reflection(message12_.message[i]);
    Message2_Set_1(message2_.message[i], &s_);
    Reflection(message14_.message[i]);
    Serialize(message1_.other_message[i], &message1_.string[i]);
    Message19_Get_2(message19_.message[i]);
    Reflection(message14_.message[i]);
    ByteSize(message14_.message[i]);
    Destroy(message14_.message[i]);
    message14_.message[i] = google::protobuf::Arena::Create<Message14>(arena_);
    Message14_Set_2(message14_.message[i], &s_);
    Copy(message17_.message[i], message17_.other_message[i]);
    Copy(message5_.message[i], message5_.other_message[i]);
    Descriptor(message19_.message[i]);
    Reflection(message12_.message[i]);
    Destroy(message6_.message[i]);
    Destroy(message6_.other_message[i]);
    Serialize(message0_.other_message[i], &message0_.string[i]);
    Serialize(message3_.message[i], &message3_.string[i]);
    Destroy(message10_.message[i]);
    message10_.message[i] = google::protobuf::Arena::Create<Message10>(arena_);
    Message10_Set_2(message10_.message[i], &s_);
    Reflection(message1_.message[i]);
    Destroy(message17_.message[i]);
    Destroy(message17_.other_message[i]);
    SpaceUsed(message8_.message[i]);
    Destroy(message10_.message[i]);
    Destroy(message10_.other_message[i]);
    Merge(message8_.message[i], message8_.other_message[i]);
    Copy(message8_.message[i], message8_.other_message[i]);
    Reflection(message19_.message[i]);
    Reflection(message19_.message[i]);
    Reflection(message5_.message[i]);
    Copy(message0_.message[i], message0_.other_message[i]);
    Reflection(message3_.message[i]);
    Swap(message0_.message[i], message0_.other_message[i]);
    Destroy(message2_.message[i]);
    Destroy(message2_.other_message[i]);
    Message8_Set_4(message8_.message[i], &s_);
    Serialize(message19_.other_message[i], &message19_.string[i]);
    Swap(message5_.message[i], message5_.other_message[i]);
    Reflection(message8_.message[i]);
    Destroy(message1_.other_message[i]);
    message1_.other_message[i] = google::protobuf::Arena::Create<Message1>(arena_);
    Message1_Set_2(message1_.other_message[i], &s_);
    Descriptor(message5_.message[i]);
    Destroy(message0_.message[i]);
    message0_.message[i] = google::protobuf::Arena::Create<Message0>(arena_);
    Message0_Set_2(message0_.message[i], &s_);
    Copy(message3_.message[i], message3_.other_message[i]);
    Copy(message1_.message[i], message1_.other_message[i]);
    Deserialize(message5_.other_message[i], &message5_.string[i]);
    Deserialize(message18_.other_message[i], &message18_.string[i]);
    Reflection(message5_.message[i]);
    Destroy(message12_.message[i]);
    message12_.message[i] = google::protobuf::Arena::Create<Message12>(arena_);
    Message12_Set_2(message12_.message[i], &s_);
    Copy(message4_.message[i], message4_.other_message[i]);
    Swap(message5_.message[i], message5_.other_message[i]);
    ByteSize(message4_.message[i]);
    Copy(message0_.message[i], message0_.other_message[i]);
    Reflection(message14_.message[i]);
    ByteSize(message0_.message[i]);
    Reflection(message0_.message[i]);
    Destroy(message8_.message[i]);
    message8_.message[i] = google::protobuf::Arena::Create<Message8>(arena_);
    Message8_Set_2(message8_.message[i], &s_);
    Message3_Set_1(message3_.message[i], &s_);
    Reflection(message19_.message[i]);
    Reflection(message18_.message[i]);
    Destroy(message19_.message[i]);
    Destroy(message19_.other_message[i]);
    Swap(message1_.message[i], message1_.other_message[i]);
    Reflection(message3_.message[i]);
    Reflection(message14_.message[i]);
    Destroy(message14_.other_message[i]);
    message14_.other_message[i] = google::protobuf::Arena::Create<Message14>(arena_);
    Message14_Set_2(message14_.other_message[i], &s_);
    Copy(message4_.message[i], message4_.other_message[i]);
    Destroy(message14_.message[i]);
    Destroy(message14_.other_message[i]);
    Swap(message0_.message[i], message0_.other_message[i]);
    Message1_Set_4(message1_.message[i], &s_);
    Copy(message4_.message[i], message4_.other_message[i]);
    Copy(message1_.message[i], message1_.other_message[i]);
    Serialize(message0_.message[i], &message0_.string[i]);
    Descriptor(message12_.message[i]);
    Reflection(message3_.message[i]);
    Destroy(message18_.message[i]);
    Destroy(message18_.other_message[i]);
    Copy(message8_.message[i], message8_.other_message[i]);
    Reflection(message5_.message[i]);
    Serialize(message4_.message[i], &message4_.string[i]);
    Copy(message5_.message[i], message5_.other_message[i]);
    Reflection(message1_.message[i]);
    Message1_Set_1(message1_.message[i], &s_);
    SpaceUsed(message5_.message[i]);
    Copy(message5_.message[i], message5_.other_message[i]);
    Destroy(message0_.message[i]);
    Destroy(message0_.other_message[i]);
    Copy(message3_.message[i], message3_.other_message[i]);
    Copy(message12_.message[i], message12_.other_message[i]);
    Reflection(message12_.message[i]);
    Destroy(message12_.other_message[i]);
    message12_.other_message[i] = google::protobuf::Arena::Create<Message12>(arena_);
    Message12_Set_2(message12_.other_message[i], &s_);
    Deserialize(message4_.other_message[i], &message4_.string[i]);
    Reflection(message12_.message[i]);
    Reflection(message1_.message[i]);
    Destroy(message1_.message[i]);
    Destroy(message1_.other_message[i]);
    Destroy(message4_.message[i]);
    message4_.message[i] = google::protobuf::Arena::Create<Message4>(arena_);
    Message4_Set_2(message4_.message[i], &s_);
    Deserialize(message3_.message[i], &message3_.string[i]);
    Reflection(message5_.message[i]);
    Destroy(message8_.message[i]);
    Destroy(message8_.other_message[i]);
    Copy(message5_.message[i], message5_.other_message[i]);
    Merge(message5_.message[i], message5_.other_message[i]);
    Merge(message5_.message[i], message5_.other_message[i]);
    Message12_Get_2(message12_.message[i]);
    Destroy(message3_.message[i]);
    message3_.message[i] = google::protobuf::Arena::Create<Message3>(arena_);
    Message3_Set_2(message3_.message[i], &s_);
    Reflection(message5_.message[i]);
    Copy(message5_.message[i], message5_.other_message[i]);
    Descriptor(message4_.message[i]);
    Copy(message4_.message[i], message4_.other_message[i]);
    Destroy(message3_.other_message[i]);
    message3_.other_message[i] = google::protobuf::Arena::Create<Message3>(arena_);
    Message3_Set_2(message3_.other_message[i], &s_);
    Copy(message12_.message[i], message12_.other_message[i]);
    Deserialize(message12_.message[i], &message12_.string[i]);
    Copy(message3_.message[i], message3_.other_message[i]);
    Destroy(message12_.message[i]);
    Destroy(message12_.other_message[i]);
    Copy(message4_.message[i], message4_.other_message[i]);
    Descriptor(message4_.message[i]);
    Destroy(message5_.message[i]);
    Destroy(message5_.other_message[i]);
    Reflection(message3_.message[i]);
    Reflection(message4_.message[i]);
    Message4_Get_3(message4_.message[i]);
    Reflection(message3_.message[i]);
    Reflection(message3_.message[i]);
    Reflection(message4_.message[i]);
    Copy(message4_.message[i], message4_.other_message[i]);
    ByteSize(message3_.message[i]);
    Deserialize(message3_.other_message[i], &message3_.string[i]);
    Reflection(message3_.message[i]);
    Merge(message3_.message[i], message3_.other_message[i]);
    Swap(message4_.message[i], message4_.other_message[i]);
    Deserialize(message4_.message[i], &message4_.string[i]);
    Descriptor(message4_.message[i]);
    Destroy(message3_.other_message[i]);
    message3_.other_message[i] = google::protobuf::Arena::Create<Message3>(arena_);
    Message3_Set_2(message3_.other_message[i], &s_);
    Destroy(message4_.message[i]);
    Destroy(message4_.other_message[i]);
    Reflection(message3_.message[i]);
    Serialize(message3_.other_message[i], &message3_.string[i]);
    ByteSize(message3_.message[i]);
    Destroy(message3_.message[i]);
    message3_.message[i] = google::protobuf::Arena::Create<Message3>(arena_);
    Message3_Set_2(message3_.message[i], &s_);
    Destroy(message3_.other_message[i]);
    message3_.other_message[i] = google::protobuf::Arena::Create<Message3>(arena_);
    Message3_Set_2(message3_.other_message[i], &s_);
    Message3_Get_1(message3_.message[i]);
    Copy(message3_.message[i], message3_.other_message[i]);
    ByteSize(message3_.message[i]);
    Copy(message3_.message[i], message3_.other_message[i]);
    Copy(message3_.message[i], message3_.other_message[i]);
    Deserialize(message3_.message[i], &message3_.string[i]);
    Reflection(message3_.message[i]);
    Destroy(message3_.message[i]);
    Destroy(message3_.other_message[i]);
  }
}

}  // namespace fleetbench::proto
